.github/workflows/deploy.yaml
.github/workflows/lint.yaml
.markdownlint.json
.pre-commit-config.yaml
CODEOWNERS
README.md
flake8
images/peer/Dockerfile
pylintrc
pyproject.toml

1, 3 items from: https://github.com/populationgenomics/analysis-runner/issues/333
- Makes the CODEOWNERS over the new `images/` directory.
- Adds `peer` Dockerfile as an example.
- Adds GH action for deploying images
- Adds linting for repository (including Hadolint for linting Dockerfiles).

Add GitHub action + linting

---

images/peer/Dockerfile

Add in pandas package in order to successfully import covariates file with different data types

Add in pandas package

---

images/str-r/Dockerfile

Image containing R packages for STR analysis.

str-r image Dockerfile

---

images/str-r/Dockerfile

edit str-R dockerfile

---

images/multipy/Dockerfile

Get latest version of multipy, so that xranges issue/non-compatability with Python3 issue is fixed

Install from repo

---

images/hap.py/Dockerfile

Housekeeping PR to resolve earlier linter issues I created

Housekeeping: fix linter warnings

---

images/hap.py/Dockerfile

the ARG line used == instead of = 🤦 
Correction here to pass the correct arg/default to the build instructions

corrected syntax error

---

images/hail-gcp-notebook/Dockerfile

Attempt based on https://stackoverflow.com/questions/70535237/how-to-update-python-on-vertex-ai-notebooks.

Install Python 3.10 in Hail notebook image

---

images/multipy/Dockerfile

Context: https://github.com/populationgenomics/analysis-runner/pull/532

Default to latest driver image for Multipy

---

images/vep/Dockerfile

I removed a no-install-recommends to try and make the linter happy - this broke the build

remove no-install-recommends

---

.github/workflows/toml-changed.yaml

Rebuild images only for changed/added tags in TOML.
Stacked on https://github.com/populationgenomics/images/pull/50

Build only for changed tags

---

images/cellregmap/Dockerfile

I need to use CellRegMap functions that are not yet released to PyPI, so installing directly from github (but not 100% sure of the syntax!). Thanks!

install latest CellRegMap from github in image

---

images.toml
images/dragmap/Dockerfile

This image doesn't segfault, in contrast to the conda binary (#66):
https://batch.hail.populationgenomics.org.au/batches/396775/jobs/1

Fix Dockerfile syntax

---

images/vep/Dockerfile

Reformat VEP Dockerfile

---

images/haplocheckcli/Dockerfile

This programm is part of the mito calling pipeline. It 
does not have releases so I am not sure if I have this right. I copied the git logic from saige-qtl.

Add haplocheck

---

images/hail-gcp-notebook/Dockerfile

And remove old sample-metadata library

Install metamist on hail-gcp-notebook image

---

.github/workflows/deploy_container.yaml

Modify the target artifactory depending on branch (main vs. non-main) status

Modify docker builder workflow

---

images/strvctvre/Dockerfile

Adds Tabix, changes the Workdir
Not changing the image version/tag, so this will need a manual rebuild

Adds Tabix

---

images/saige-qtl/Dockerfile

Apologies, hopefully last one!

update to only include files that are actually there

---

images/exomiser/template.yaml

One of these TSVs should be ready to plug'n'play in Seqr

Request additional exomiser output formats

---

images/vep_105/Dockerfile

See https://github.com/populationgenomics/images/pull/132#discussion_r1506728301
Closes #111

Fix VEP_105 builder

---

images/saige-qtl/Dockerfile

Cf PR #163 — We need to be able to build other commits in addition to the HEAD of the default branch.

Retrieve all commits when cloning saige-qtl

---

images/cpg_hail/Dockerfile
images/cpg_hail_gcloud/Dockerfile

Follow-on from #227 
Uses the new-Hail base image in the hail-gcloud image

Bump to new hail (gcloud edit.)

---

images/r-meta/Dockerfile

r-rfast is a utilities package in R that is supposed to speed up susieR for big inputs.

Add r-rfast to r-meta packages

---

images/manta_noRRRforINS/Dockerfile

See https://github.com/populationgenomics/gatk-sv/pull/30

Add Manta dockerfile that disables RRR for INS detection

---

images/bcftools/Dockerfile

Update bcftools to 1.21

---

images/gatk/Dockerfile

Build of GATK, BCFtools, and gcloud from release

Gatk 4620 manual
