- .github/workflows/deploy.yaml
It's called `github.event` not `github.events`
> Fix github.event name

- images/peer/Dockerfile
To allow this image to be used as a Hail batch python_job
> Add dill to peer image 

- images/reviewer/Dockerfile
Unable to build using GitHub Actions. 
Standard output recommended adding --no-check-certificate to overcome exit code 5 error.
> Altered REViewer dockerfile

- .github/workflows/deploy.yaml
I assumed that the syntax for a github workflow would be wrapping in ${braces}, but the arguments were passed as:
```Run docker build --tag $DOCKER_IMAGE images/$***IMAGE_NAME***/ --build-arg VERSION=$***IMAGE_TAG***```
Based on syntax from the documentation:
```
If you need to use a workflow run's URL from within a job, you can combine these environment variables: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
```
There is no brace protection required for a path featuring values between slashes
> remove flanking braces for env vars

- .github/workflows/deploy.yaml
- images/hap.py/Dockerfile
The variable expansion for `${VERSION}` inside the docker build is still coming out as `***VERSION***` instead of 0.3.15, even though the Docker instructions suggest this should be passed correctly:
see https://github.com/populationgenomics/images/runs/7721337852?check_suite_focus=true
https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
```
docker build --tag $DOCKER_IMAGE images/$IMAGE_NAME/ --build-arg VERSION=$IMAGE_TAG
shell: /usr/bin/bash -e ***0***
env:
DOCKER_BUILDKIT: 1
BUILDKIT_PROGRESS: plain
CLOUDSDK_CORE_DISABLE_PROMPTS: 1
DOCKER_IMAGE: australia-southeast1-docker.pkg.dev/cpg-common/images/hap.py
IMAGE_NAME: hap.py
IMAGE_TAG: 0.3.15
```
I think there's something I'm not seeing here, so I'd really welcome eyes/improvements!
> no braces, slight tweak to arg passing

- images/hap.py/Dockerfile
Finally managed to build this locally! I've tested that `hap.py` and `pre.py` are both in $PATH, and the env variable $RTG_JAR is set and functional
Confirmed with the Hap.py codebase that the python version supported is <=2.7.3, so we need an install environment for python2. As a result I've reverted the base image Ubuntu 22.04 -> 18.04.
It did get stuck on the Hap.py/RTG install during my first local attempt, then on a retry it built smoothly (one to watch on the deploy pipeline)
> Revert to earlier ubuntu for python2

- images/hap.py/Dockerfile
The latest change of the hap.py image was to bring the hap.py codebase up to date (inc. the bundled version of RTG tools)
This has not updated the SAM/BCFtools versions which are included, currently 1.4.1 (2017)
This tweak to the build file updates the versions of both tools to 1.15.1, and adds a configurable build hts_version argument to update again in future
Tested on a local build - bcftools and samtools are both distributed with an internal HTSlib that they are compiled with, so this should not have any downstream implications
There is at least one command for Hap.py that uses a deprecated argument, but BCFtools transparently changes this to the correct form and issues a warning
> Update sam and bcftools

- images/vep/Dockerfile
The `main` branch of loftee causes a ton of error logging messages when running on GRCh38.
Example [here](https://batch.hail.populationgenomics.org.au/batches/378307/jobs/17)  (similar errors being throw 27000+ times during processing of one variant subset)
There is a separate branch which we can use instead, with an updated version of the plugin files, see https://github.com/konradjk/loftee/issues/84 (and other similar issues)
The path to copy the plugin files to contains a `*` - 
-  for VEP 105.0, the path is /root/micromamba/share/ensembl-vep-105.0-1
- for 107.0 this is /root/micromamba/share/ensembl-vep-107.0-0
This copy works for both situations when building the image, but doesn't resolve hard-coding like [this](https://github.com/populationgenomics/production-pipelines/blob/main/job …
> updates the loftee plugin

- images/vep/Dockerfile
Quite a few alterations here... Please review
1. LoF doesn't compile due to `pm`/`pl` files being unable to find each other, see https://github.com/konradjk/loftee/issues/60. Solution used - https://github.com/populationgenomics/loftee_38, a fork of grch38 from LOFTEE which moves all required files into the same folder, and updates import paths accordingly. Remove all loftee plugin content from the default VEP content, and added all files manually from the github clone. Adds this path as env PERL5LIB (see https://github.com/konradjk/loftee/issues/84#issuecomment-1025776382)
2. Perl module BigFile for `.bw` queries is not installed - added `perl-bio-bigfile` to the conda installation (see https://github.com/sigven/cpsr/issues/21
3. LoF doesn't compile due to BioPerl being unavailable …
> Fixes to LOFTEE plugin in VEP build

- images/cellregmap/Dockerfile
Context: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1666739262508909?thread_ts=1666679167.721159&cid=C018KFBCR1C
Remaining hadolint errors are for `vep` image only.
> Add cellregmap Dockerfile

- images/stripy/Dockerfile
I spent a while this morning building up a dockerfile, then realised that STRipy already has a dockerfile... just not in the STRipy repo 🙃 
sourced from https://stripy.org/Dockerfile, with a samtools version bump
> add STRipy Dockerfile

- images/stripy/Dockerfile
adds gcs_fuse (useful in connecting reference data without copying into container)
> Add `gcsfuse` into `stripy` image

- .pre-commit-config.yaml
- images/stripy/Dockerfile
Add the gcloud sdk to the stripy image. For right or wrong, I have done this install as per google's instructions not the conda aproach cpg seems to typically use.
> add gcloud to stripy

- images/bgt/Dockerfile
Posting a multistage build alternative, after discussions on reducing image sizes to reduce overall job setup/image pulling times.
Would appreciate feed back on whether this is a good idea, and if so whether we should start trying to finesse our more frequently used images
> multistage version, image size from ~400MB to 80MB

- images/basespace/Dockerfile
A container image based on the AR driver base, which just installs BaseSpace CLI to the $HOME/bin/bs directory
See https://github.com/populationgenomics/transfer-private/pull/7 for intended use
> Container with BaseSpace CLI installed

- .github/workflows/deploy_config.yaml
- .github/workflows/deploy_container.yaml
- .github/workflows/lint.yaml
The default $GITHUB_TOKEN is useful only for this populationgenomics/images repository; it has no permissions for production-pipelines. Use a suitable PAT for when the latter repo is, for example, temporarily made private for operational reasons.
The secret name used here includes `_RAW_ `to indicate that its value must be just the text of the PAT, not the `url=` / `username=` / `password=` format used in other repositories' workflows.
Unfortunately this line must be removed or commented out to revert to using the default $GITHUB_TOKEN. With the technique used in other repositories, deleting the secret means `git credential approve` doesn't add anything and it reverts to unauthenticated access. However for this workflow the token is an argument to the `actions/checkout` action and …
> Authenticate GitHub access in actions workflow

- images/ensembl-vep/Dockerfile
Burns down the previous process and starts from scratch:
- Build on the released Docker image from Ensembl (Trusting them to build their own tool...)
- Sets the user back to root so we can actually use our own image without user permission errors
- Pulling the GRCh38 version of LOFTEE and overwriting any plugins that existed previously (default = GRCh37 which is bad for us)
- Pulling in some small reference files for plugins that don't have this data packaged by default 
- utr_annotator_38.txt: 2.3MB
- pli_scores.txt: 0.5MB
- loftool_110_scores.txt: 233KB
- Pulling in the AlphaMissense plugin (hopefully should be bundled by default soon, it was only released yesterday...)
This approach scraps some stuff from the alternative `images/vep/Dockerfile` approach:
- Don't use …
> Adds a new VEP builder

- images/vep_110/Dockerfile
I previously submitted this PR: https://github.com/populationgenomics/images/pull/104
Long story short - I was adding Samtools to the image, but in the PR I incorrectly stated I was installing Tabix. John correctly identified that the image would already had Tabix installed. I had a brain fart and closed the PR, opening a new one without Samtools... Sigh.
This error has surfaced now that the image has moved to a new name (`ensembl-vep` -> `vep_110`). I built `ensembl-vep` from the branch, and `vep_110` has been built from main (no Samtools).
> Add samtools to vep 110

- .github/workflows/deploy_config.yaml
Repo is no longer private, and this expired token is crashing the deploy workflow
Also bumps the gcloud setup workflow which is available at `V1`
https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
> Remove Prod-Pipes PAT

- .github/workflows/deploy_config.yaml
- .github/workflows/deploy_container.yaml
So it looks like the new version of `google-github-actions/setup-gcloud@v1` action no longer uses `service_account_key` as input. See [this failed deploy](https://github.com/populationgenomics/images/actions/runs/6886508598/job/18732356675), under the gcloud setup header. 
```
Warning: Unexpected input(s) 'service_account_key', valid inputs are ['skip_install', 'version', 'project_id', 'install_components']
...
Warning: No authentication found for gcloud, authenticate with `google-github-actions/auth`.
```
Which is leading to a fail in the `deploy config toml` step.
```
ERROR: (gcloud.storage.cp) You do not currently have an active account selected.
Please run:
$ gcloud auth login
to obtain new credentials.
```
From the actions repo, it looks like they now require use of the …
> Update actions to use google-github-actions/auth@v1 and fix input syntax

- images/samtools/Dockerfile
The initial download of micromamba*.tar.bz2 from api.anaconda.org has recently begun failing when run under docker, presumably due to network setup changes elsewhere.
See https://centrepopgen.slack.com/archives/C03FZL2EF24/p1699837108996249 for context.
Fortunately `micromamba install …` itself still works from docker, so we can use `micromamba install -v` to observe the URL style it uses when downloading and installing other packages, and use the same hostname and URL style to do our initial manual download of the micromamba package.
> Use a similar download URL to those micromamba itself uses

- images/samtools/Dockerfile
Final fix to make a samtools image that Hail can use for its Python jobs: hail needs to run dill using the same Python version as the driver image.
This image has been built into …/images-dev and successfully used for a test run of CRAM reheadering: see <https://batch.hail.populationgenomics.org.au/batches/430054>.
> Ensure dill etc are installed for Python 3.10

- .github/workflows/deploy_config.yaml
- .github/workflows/deploy_container.yaml
In a bid to introduce better security permissions, we have replaced the use of SA keys to workload identity providers where possible. We will also ensure the workload federated identities are attached to an environment in the repo.
> Environment Lock

- images/r-meta/Dockerfile
I am making `r-meta` as an image for meta-analysis and downstream analysis after eQTL discovery - it will have `coloc` and `susieR` packages for colocalisation and finemapping analysis respectively. 
Confirming the image works in my test scripts.
> Add susieR to the dockerfile

- .github/workflows/deploy_config.yaml
- .github/workflows/deploy_container.yaml
- .github/workflows/lint.yaml
Recombine `deploy_image_prod`/`deploy_image_dev` into a single workflow by using [`${{ … }}`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example) to vary `environment` and `service_account` as appropriate. In particular, this avoids building the Docker image twice because both jobs are running in parallel.
Update the versions of the various actions used to [node20-based ones](https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/).
> Refactor deploy_image job and update actions versions used

- images.toml
- images/bcftools_120/Dockerfile
#154 was effectively abandoned because nobody (justifiably) wanted to just replace the current bcftools image which is used all over the cpg_workflows codebase
This re-opens #154 but instead of upgrading the bcftools image in place, it adds a parallel version `bcftools_120`.
@jmarshall has already polished this build down to a cool 35MB, and I've already been using the image built from #154 in production workflows... Albeit from the dev-image store, naughty.
https://github.com/populationgenomics/production-pipelines/blob/main/configs/defaults/clinvarbitration.toml#L6
Code/image duplication aside, this is a super lean build and would be a good template for lean single-tool images
> Fresh implementation of #154

- images/ica/Dockerfile
Hitting issues with running ICA pipeline using standalone ICA image [here](https://batch.hail.populationgenomics.org.au/batches/589302/jobs/1)
Adding Dill package to ICA image so that PythonJob arguments can get de/serialised.
>  Install pip inside ICA image

- .github/workflows/deploy_container.yaml
This is implementation for task: 
https://cpg-populationanalysis.atlassian.net/browse/SET-414?atlOrigin=eyJpIjoiODViMGFlNWExNjY5NDIzYWJkOGZhMDEzYTgwYWU1MDkiLCJwIjoiaiJ9
After images gets pushed to registry it shows the link in the log output.
> Show link to built image as last step of the CI.

- .github/workflows/revamp.yaml
- .github/workflows/revamp_dev.yaml
This basically copies in the changes from PR #184 to remove the step that builds images for cpg_workflows as we no longer need it. Additional details can be found on the PR above.
We also want to rename the new workflows to make them distinct.
> Remove unnecessary CI step in revamped workflow

- images/bcftools_121/Dockerfile
A bit ugly to now have three separate bcftools images, however this release comes with htslib 1.21, which has an important fix for writing indexes with the `--write-index` option while not using multiple threads. 
See a Slack discussion of a bad index being written using bcftools 1.20 [here](https://centrepopgen.slack.com/archives/C082NA58R7S/p1744173388834459?thread_ts=1744163974.749869&cid=C082NA58R7S), and the htslib 1.21 release notes detailing the bugfix [here](https://github.com/samtools/htslib/releases/tag/1.21).
> Fix issues with on-the-fly indexing of VCF/BCF (bcftools --write-index) when not using multiple threads.
> Add bcftools v1.21 dockerfile

- .github/workflows/get_version.py
- images/dummy/Dockerfile
This amends the `get_version` utility to recognise both formats of the version in a Dockerfile:
`ARG VERSION=${VERSION:-1.0}`
`ENV VERSION=1.0`
> Fix arg version format

- .github/workflows/revamp.yaml
- .github/workflows/revamp_dev.yaml
Closes #224 
The VERSION in the Dockerfile is being used as a source of truth for the builder workflow when generating a new tag.
The tags are free-form, but the package Version number is not - we can't pass in an alternative VERSION argument at build time, we need the exact version to remain unchanged. See #224
> Correction to VERSION override

- images/stripy/Dockerfile
Adds `jq` to the list of bash modules installed by `apt install`.
This is a useful bash library for json parsing, which is needed for updating the default `config.json` that comes with the stripy source code. See https://github.com/populationgenomics/production-pipelines/pull/1208
NOTE: This PR also hardcodes the stripy version "v2.5". This is because the `$VERSION` now evaluates to `"v2.5-1"` since the images overhaul, and this was preventing successful installation of the module. See comment [here](https://github.com/populationgenomics/images/pull/220#discussion_r2080913770) for an explanation.
> Install jq in stripy image

- .github/workflows/deploy.yaml
- .github/workflows/deploy_dev.yaml
- .github/workflows/get_version.py
- README.md
Followup to PR #226, this activates the revamped workflows, in particular changing _revamp.yaml_ (now named _deploy.yaml_) to write to `images` instead of `images-tmp`. 🎉 
Update the _README.md_ documentation. There are already several Dockerfiles that use the `ARG VERSION=x.y.z` syntax (without `${VERSION:- … }` wrapped around the value), so we need to update _get_version.py_ to handle that too.
> Fully activate revamped deployment actions workflows

- .github/workflows/get_version.py
See PR #233, in which one deleted _Dockerfile_ has stopped the workflow from working for other updated images.
> Ignore Dockerfiles that have been deleted by the pull request

- .github/workflows/get_version.py
The `get_version` code didn't account for file renaming after the addition of `name-status` to the `diff` command. This attempts to address that and handle renaming, addition, modification and deletion.
> Handle file renaming

- .github/workflows/deploy_dev.yaml
The validation steps in the dev deploy manual workflow were failing due to unescaped characters in the regex. This has now been fixed and a check has also been added to ensure empty docker cli args are accepted.
> Fix breaking validation step in dev deploys

- images/cpg_hail/Dockerfile
- images/multiqc/Dockerfile
Install `procps` in the cpg_hail image
- images using `cpg_hail` will need to update the version to match this one if they want procps to be included
> Install procps in cpg_hail and multiqc

- images/samtools/Dockerfile
size reduction 1.8GB -> 172MB
This was a bit of a sidetrack, the mito/stripy images contain an old samtools... I thought it might be good to build a lean samtools image and use it as a base. In any case, the one we have is fat and gross, and this should is much more space efficient
> Update SAMtools build
